### PR TITLE
Add support for pyrogram 0.8.0

### LINKED ISSUE #1: Pyrogram 0.7.5 is not supported
* tgintegration version: 0.2.4
* Pyrogram 0.7.5
* Python version: 3.6
* Operating System: Fedora 28

### Description

tgintegration does not work with Pyrogram 0.7.5

Workaround: downgrade Pyrogram 0.7.4

### What I Did
I just installed actual tgintegration library via pip and tried the Usage Example
```
Traceback (most recent call last):
  File "/home/hkoeck/PycharmProjects/resbot/tests/test_demo.py", line 12, in <module>
    client.start()
  File "/home/hkoeck/PycharmProjects/venv/lib64/python3.6/site-packages/tgintegration/botintegrationclient.py", line 62, in start
    res = super().start(debug=debug)
TypeError: start() got an unexpected keyword argument 'debug'
```

Looks like Pyrogram 0.7.5 does not support the argument debug any more

### PR DESCRIPTION
**Pull request by schafezp**
Closes #1 

There were only minor changes to make the module able to be loaded and run. I have not extensively tested any other features but at least this PR will make the module usable again with pyrogram 0.8.0 and tgcrypto 1.1.1

### CODE REVIEW

**Comment by JosXa** [comment]
Hi @schafezp, thank you for your PR and sorry for the late reply. I am working on updating the library to the latest asyncio version of Pyrogram including a redesign, so your changes have become obsolete - But I think you will be happy with the results :)
