### ISSUE TITLE
Pyrogram 0.7.5 is not supported

### ISSUE THREAD

**Issue by hkoeck** [JosXa/tgintegration#1]
* tgintegration version: 0.2.4
* Pyrogram 0.7.5
* Python version: 3.6
* Operating System: Fedora 28

### Description

tgintegration does not work with Pyrogram 0.7.5

Workaround: downgrade Pyrogram 0.7.4

### What I Did
I just installed actual tgintegration library via pip and tried the Usage Example
```
Traceback (most recent call last):
  File "/home/hkoeck/PycharmProjects/resbot/tests/test_demo.py", line 12, in <module>
    client.start()
  File "/home/hkoeck/PycharmProjects/venv/lib64/python3.6/site-packages/tgintegration/botintegrationclient.py", line 62, in start
    res = super().start(debug=debug)
TypeError: start() got an unexpected keyword argument 'debug'
```

Looks like Pyrogram 0.7.5 does not support the argument debug any more

**Comment by puzanov** [comment]
Same error.

**Comment by JosXa** [comment]
Hi @hkoeck, @puzanov, thanks for the report!

This will be fixed in the upcoming v1 release 🎊

**Comment by JosXa** [comment]
https://github.com/JosXa/tgintegration/releases/tag/v1.0
Enjoy :)
